### ISSUE TITLE
temp hp aura not updating

### ISSUE THREAD

**Issue by bain2236** [cyruzzo/AboveVTT#347]
aura updates for the player but doesn't appear to sync with DM.
Sometimes a token has their temp hp added to their current hp and sometimes not. Not been able to find out why there's an inconsistency

https://user-images.githubusercontent.com/9283242/160240358-2f411fc1-f231-4c88-83d6-5c3675ac060f.mp4

**Comment by bain2236** [comment]
I'll have to do another double check of the aura sync issue tomorrow

**Comment by vlaminck** [comment]
@bain2236 when you get a chance, can you validate this issue? Seems like it may have been resolved.

**Comment by bain2236** [comment]
Still an issue by the looks, at least for calculating the correct health colour.
DM appears to have hp and then temp hp. which makes for the orange and blue border. that token has 3hp and 5 temp hp
Player does show that it has temp hp, but shows it's at full health because I thinkn it's combining the temp hp and hp.
Whatever changes have been made in the direction of this bug do sort of resolve it. At least now you can see that a player has temp hp, regardless of if you're the DM or the player. 
Now it's just the DM gets more detailed colouring of the actual health of the player via the aura. Which I guess is also fine?
![image](https://user-images.githubusercontent.com/9283242/166416394-53270792-4bdd-4d66-8152-3b9a58a7841a.png)
